apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bmb-cron-scaledobject
  namespace: duploservices-dev-server
spec:
  scaleTargetRef:
    name: bmb
  minReplicaCount: 0
  cooldownPeriod: 200
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 0 6 * * 1
      end: 0 23 * * 6
      desiredReplicas: "1"
